### ISSUE TITLE
I NEED UR HELP BROTHER

### ISSUE THREAD

**Issue by ELVISKUNDY** [Sphinxroot/iptv-tool#1]
I LIVE IN THE CONTRY CALLED TANZANIA THERE THIS WEBSITE https://kabanga.ga/ I WANT TO TAKE STREAMING LINKS AND CREATE MY OWN M3U FILE BUT THEIR STREAMING FORMAT ARE IN mpd format how do i change it to m3u8 BECAUSE I CANT PLAY MPD FILE IN TIVIMATE there a way to stream those mpd links with app like kodi if so ho do i create file in kodi ur help sir

**Comment by Sphinxroot** [comment]
sorry for the late reply .. didnt see this yet

as for exemple  :
https://kabanga.ga/azamtv/watch/?c=1427056744

https://1427056744.rsc.cdn77.org/1427056744/Manifest.mpd

Widevine DMR Protected
seem to be generated from here https://azy4sj9b.anycast.nagra.com/AZY4SJ9B/wvls/contentlicenseservice/v1/licenses
and inside there  isa base64 expirable token

but if you change  to HSL 
https://1427056744.rsc.cdn77.org/1427056744/Manifest.m3u8

this is inside

#EXTM3U
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,RESOLUTION=-1x240,FRAME-RATE=30.000,CODECS="avc1.64001e,mp4a.40.2",AVERAGE-BANDWIDTH=690000,BANDWIDTH=870000
tracks-v3a1/mono.m3u8
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,RESOLUTION=-1x360,FRAME-RATE=30.000,CODECS="avc1.64001e,mp4a.40.2",AVERAGE-BANDWIDTH=980000,BANDWIDTH=1220000
tracks-v2a1/mono.m3u8
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,RESOLUTION=-1x432,FRAME-RATE=30.000,CODECS="avc1.64001e,mp4a.40.2",AVERAGE-BANDWIDTH=1220000,BANDWIDTH=1520000
tracks-v1a1/mono.m3u8

 if i add referrer and/or User-Agent  they Still dont work  ( tested On : Kodi , Potplayer ,VLC  )

https://1427056744.rsc.cdn77.org/1427056744/tracks-v1a1/mono.m3u8


some factor maybe:

web site have " strict-origin-when-cross-origin"

access-control-allow-headers
	x-vsaas-session, x-no-redirect, origin, authorization, x-real-ip, accept, range
access-control-allow-methods
	GET, PUT, DELETE, OPTIONS
access-control-allow-origin
	*
access-control-expose-headers
	Server, range, X-Run-Time, Content-Length, Location
